apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  namespace: ktpm
spec:
  serviceName: db-service
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: {{ .Values.db.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.db.env.POSTGRES_DB }}
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.db.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.db.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: ktpm
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}