# jenkins.yaml
# --- 1. Namespace ---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
# --- 2. Service Account & Role Binding ---
# Cung cấp quyền hạn cần thiết cho Jenkins
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-admin
    namespace: jenkins
roleRef:
  kind: ClusterRole
  name: jenkins-admin-role
  apiGroup: rbac.authorization.k8s.io
---
# --- 3. Persistent Volume Claim ---
# Yêu cầu một không gian lưu trữ để dữ liệu Jenkins không bị mất
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  # storageClassName: "standard" # Bỏ comment nếu bạn cần chỉ định StorageClass cụ thể
---
# --- 4. Jenkins Deployment ---
# Định nghĩa cách chạy Pod Jenkins
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11 # Sử dụng image chính thức
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
---
# --- 5. Jenkins Service ---
# Lộ Jenkins ra ngoài để có thể truy cập
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort # Dùng NodePort để dễ demo
  selector:
    app: jenkins
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
      nodePort: 32000 
    - name: jnlpport
      port: 50000
      targetPort: 50000