apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vdt-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Maybetuandat/vdt_db'
    targetRevision: HEAD
    path: 'database-chart'
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vdt-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true