- name: Remove conflicting containerd package
  apt:
    name: containerd
    state: absent

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable"
    filename: docker
    state: present
    update_cache: yes

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Create config directory
  file:
    path: /opt/prometheus
    state: directory

- name: Copy Prometheus config file
  copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml