apiVersion: v2
name: my-app
description: A simple microservice app with frontend and backend
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: backend-api
    version: 0.1.0
    repository: "file://charts/backend-api"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
