backend-api:
  replicaCount: 4
  image:
    repository: shiner2/backend-api
    tag: v1.0.5
  service:
    type: NodePort
    port: 5000
    nodePort: 30500

frontend:
  replicaCount: 4
  image:
    repository: shiner2/frontend
    tag: v1.0.3
  service:
    type: NodePort
    port: 80
    nodePort: 30081
