apiVersion: v1
clusters:
- cluster:
    server: https://34.68.185.144:6443
    insecure-skip-tls-verify: true
  name: cluster.local
contexts:
- context:
    cluster: cluster.local
    user: kubernetes-admin
  name: kubernetes-admin@cluster.local
current-context: kubernetes-admin@cluster.local
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: <certificate>
    client-key-data: <certificate_key>