- name: Run Elasticsearch container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    state: started
    restart_policy: always
    ports:
      - "9200:9200"
    env:
      discovery.type: single-node
