apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-webapp-monitor-1
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: user-service
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - targetPort: 8000
      interval: 10s
      scheme: http
      path: /metrics