# file: deploy_prometheus.yml
- name: Deploy and Configure Prometheus Container
  hosts: localhost  # Chạy trên chính máy đang thực thi playbook
  connection: local
  become: yes       

  tasks:
    - name: Create directory for Prometheus configuration
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    - name: Copy Prometheus configuration file
      copy:
        src: ./prometheus.yml  
        dest: /etc/prometheus/prometheus.yml

    - name: Ensure old prometheus container is removed
      docker_container:
        name: prometheus-server
        state: absent

    - name: Run Prometheus container
      docker_container:
        name: prometheus-server
        image: prom/prometheus:latest
        state: started
        restart_policy: always
        ports:
          # Expose cổng 9090 của container ra cổng 9090 của master node
          - "9090:9090"
        volumes:
          - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml