- name: Run Kibana container
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    state: started
    restart_policy: always
    ports:
      - "5601:5601"
    env:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    links:
      - elasticsearch
