---
- name: Deploy HAProxy Loadbalancer
  hosts: haproxy_server
  become: true
  tasks:
    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Copy haproxy.cfg to target
      ansible.builtin.copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'

    - name: Restart HAProxy service
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
        enabled: yes


