# kaniko-pod-template.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build
  namespace: default
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug 
    imagePullPolicy: Always
    command:
    - /busybox/cat # Giữ cho container chạy để Jenkins exec vào
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      secret:
        secretName: your-dockerhub-secret 
        items:
          - key: .dockerconfigjson
            path: config.json