global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['192.168.122.190:32336']
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.122.190:32337']