apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'bluemoon-be'
        static_configs:
          - targets: ['be-service.ktpm.svc.cluster.local:8000']
      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service.ktpm.svc.cluster.local:3000']
