apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data
    server: 192.168.122.87
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage