apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logging
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.17
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://192.168.122.107:9200
---
apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: kibana
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 32338
  selector:
    app: kibana