global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API trên Kubernetes
  - job_name: 'vdt-backend-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.122.93:30002']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'vdt-backend-api'
      - source_labels: [__address__]
        target_label: application
        replacement: 'student-management-backend'

  # Frontend Nginx metrics trên Kubernetes
  - job_name: 'vdt-frontend-nginx'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.122.93:30113']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'vdt-frontend-nginx'
      - source_labels: [__address__]
        target_label: application
        replacement: 'student-management-frontend'