apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
      nodePort: 32443
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort