apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: https://github.com/chuitrai/my_app_config.git
    targetRevision: HEAD      
    path: .                  
    helm:
      releaseName: my-app     
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-final-project-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true    
