# Default values for my-app-chart.

backend: 
  replicaCount: 1
  image:
    repository: chuitrai2901/my-go-backend
    pullPolicy: IfNotPresent
    tag: "v1.0.0" #backend-tag  
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

frontend:
  replicaCount: 1
  image:
    repository: chuitrai2901/my-react-frontend # <-- Thay bằng tên image của bạn
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: NodePort
    port: 80

database:
  image:
    repository: postgres
    tag: "14-alpine"
  
  # Cấu hình sẽ được ghi đè bởi repo config
  dbName: "mydb"
  username: "admin"
  password: "123"

  # Cấu hình lưu trữ
  storageClass: "local-path" # Giả định bạn dùng Local Path Provisioner
  storageSize: "1Gi"
  tag: "v1.0.0" #frontend-tag  