controller:
  admin:
    password: admin
    username: admin
  installPlugins:
  - kubernetes
  - workflow-aggregator
  - git
  - configuration-as-code
  - docker-plugin
  - github
  - generic-webhook-trigger
  - ws-cleanup
  persistence:
    enabled: false
  serviceType: NodePort
  servicePort: 8080
  targetPort: 8080
  nodePort: 30080
  service:
    protocol: TCP
  JCasC:
    defaultConfig: true
    configScripts:
      jenkins-config: |
        jenkins:
          clouds:
          - kubernetes:
              name: "kubernetes"
              namespace: "jenkins"
              jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
              jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
              containerCapStr: "10"
              connectTimeout: 5
              readTimeout: 15
              skipTlsVerify: false
              maxRequestsPerHostStr: "32"
              retentionTimeout: 5
              waitForPodSec: 600
              serverUrl: "https://kubernetes.default"
              podLabels:
              - key: "jenkins/jenkins-jenkins-agent"
                value: "true"
              templates:
              - name: "docker-builder"
                namespace: "jenkins"
                label: "docker-builder"
                nodeUsageMode: "NORMAL"
                podRetention: "Never"
                idleMinutes: 0
                instanceCap: 2147483647
                serviceAccount: "default"
                slaveConnectTimeout: 100
                showRawYaml: true
                yamlMergeStrategy: "override"
                containers:
                - name: "jnlp"
                  image: "jenkins/inbound-agent:4.13.0-1-alpine"
                  args: "^${computer.jnlpmac} ^${computer.name}"
                  workingDir: "/home/jenkins/agent"
                  ttyEnabled: false
                  resourceRequestCpu: "200m"
                  resourceRequestMemory: "256Mi"
                  resourceLimitCpu: "500m"
                  resourceLimitMemory: "512Mi"
                - name: "docker"
                  image: "docker:24.0.7-cli"
                  workingDir: "/home/jenkins/agent"
                  ttyEnabled: true
                  command: "cat"
                  args: ""
                  resourceRequestCpu: "200m"
                  resourceRequestMemory: "256Mi"
                  resourceLimitCpu: "500m"
                  resourceLimitMemory: "512Mi"
              - name: "default-agent"
                namespace: "jenkins"
                label: "jenkins-agent"
                nodeUsageMode: "NORMAL"
                podRetention: "Never"
                containers:
                - name: "jnlp"
                  image: "jenkins/inbound-agent:4.13.0-1-alpine"
                  args: "^${computer.jnlpmac} ^${computer.name}"
                  workingDir: "/home/jenkins/agent"
                  resourceRequestCpu: "100m"
                  resourceRequestMemory: "128Mi"
                  resourceLimitCpu: "300m"
                  resourceLimitMemory: "256Mi"