apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
    # app.kubernetes.io/part-of: argocd
  ports:
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30082